apiVersion: v1
kind: BuildConfig
metadata:
  name: httpd
spec:
  output:
    to:
      kind: ImageStreamTag
      name: httpd:latest
  source:
    dockerfile: |-
      FROM centos/httpd-24-centos7:latest
      COPY /opt/app-root/src/html/* /opt/rh/httpd24/root/var/www/html/
    images:
    - from:
        kind: ImageStreamTag
        name: jekyll-serve:prod
      paths:
      - sourcePath: /opt/app-root/src/html/*
        destinationDir: "."
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: httpd-24-centos7:latest
  triggers:
  - imageChange: {}
    type: ImageChange

