

apiVersion: v1
kind: BuildConfig
metadata:
  name: image-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: image-build:latest
  source:
    type: Dockerfile
    dockerfile: |-
        FROM httpd-24-centos7:latest
        COPY /opt/app-root/src/* /opt/rh/httpd24/root/var/www/html
    images:
    - from: 
        kind: ImageStreamTag
        name: artifact-image:latest
      paths: 
      - sourcePath: /opt/app-root/src/.
        destinationDir: "."
  strategy:
    dockerStrategy:
      from: 
        kind: ImageStreamTag
        name: httpd-24-centos7:latest
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange


