apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: s2i-jekyll
    name: s2i-base-rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/rhscl/s2i-base-rhel7:latest
      name: latest
      referencePolicy:
        type: Source
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
