apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: httpd-24-centos7
    name: httpd-24-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: centos/httpd-24-centos7:latest
      from:
        kind: DockerImage
        name: centos/httpd-24-centos7:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ruby-25-centos7
    name: ruby-25-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: centos/ruby-25-centos7
      from:
        kind: DockerImage
        name: centos/ruby-25-centos7
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
